### ISSUE TITLE
Select is using not allowed aria-expanded attribute

### ISSUE THREAD

**Issue by maspychaj-sage** [Sage/carbon#4891] opened 2022-02-24 11:21 UTC
### Current behaviour

![image](https://user-images.githubusercontent.com/75613789/155514525-c90849b8-5a77-4749-8229-04d57c52b58e.png)

### Expected behaviour

Attribute should be removed or different role should be used.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/select--default-story

### JIRA Ticket (Sage Only)

SBS-21245

### Carbon Version

104.30.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment] 2022-02-24 15:44
Duplicate of https://github.com/Sage/carbon/issues/4840

**Closed by samtjo** 2022-02-24 15:44 UTC
Labels: Bug, triage
