### ISSUE TITLE
Date picker - Required ARIA attributes must be provided (Axe: Critical)

### ISSUE THREAD

**Issue by glen-hoad** [Sage/carbon#6351] opened 2023-10-05 16:40 UTC
### Current behaviour

Issue reported by AXE tool when the Carbon date picker control is open.

Required ARIA attributes must be provided. This will apply to all date pickers in the web.
<div class="DayPicker-Caption" role="heading" aria-live="polite"><div>January 2023</div></div>

### Expected behaviour

No critical accessibility errors reported for date picker

### CodeSandbox or Storybook URL

https://codesandbox.io/s/zen-orla-rygdph?file=/src/App.js

### Suggested Solution

Resolve issues reported by AXE tooling on the datepicker control.

### Carbon Version

Current

### Design Tokens Version

N/A

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment] 2023-10-10 11:01
duplicate of #5804

**Closed by edleeks87** 2023-10-10 11:01 UTC
Labels: Bug, triage
