### ISSUE TITLE
Bulk Actions - Form elements must have labels.

### ISSUE THREAD

**Issue by RavishankarSage** [Sage/carbon#5521] opened 2022-10-03 11:35 UTC
### Current behaviour

In relation to the  Bulk actions screen once employees have been created -  Form Elements must have labels
![carbon-issues](https://user-images.githubusercontent.com/109725018/193567236-fbc99648-440d-4d01-948a-b7166ba05e3b.png)

### Expected behaviour

 Ensures every form element has a label.

### CodeSandbox or Storybook URL

https://carbon.sage.com/v/109.2.2/index.html?path=/docs/flat-table-expandable--paginated

### JIRA Ticket (Sage Only)

SKPU-7520

### Carbon Version

109.2.2

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment] 2022-10-03 12:41
Duplicate of #5284

**Closed by edleeks87** 2022-10-03 12:41 UTC
Labels: Bug, triage
