### ISSUE TITLE
[Date picker] Buttons must have discernible text (Axe: Critical)

### ISSUE THREAD

**Issue by glen-hoad** [Sage/carbon#6352] opened 2023-10-05 16:47 UTC
### Current behaviour

"Date picker- discernible text"

<button type="button" class="sc-fYiAbW jytvGH"><span class="sc-bZQynM gKKvNQ" data-element="chevron_left" font-size="small" type="chevron_left" data-component="icon"></span></button>

Left chevron/button is not accessible.

### Expected behaviour

Date picker should not report any critical accessibility issues through AXE.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/zen-orla-rygdph?file=/src/App.js

### Suggested Solution

Make the date picker accessible.

### Carbon Version

Current

### Design Tokens Version

N/A

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment] 2023-10-10 11:01
duplicate of #5804

**Closed by edleeks87** 2023-10-10 11:01 UTC
Labels: Bug, triage
