### ISSUE TITLE
Unit Test on radio button: Warning appears when we run unit test on radio button.

### ISSUE THREAD

**Issue by jerlau** [Sage/carbon#3421] opened 2020-11-23 15:01 UTC
### Current behaviour
run unit test on a radio button raises this warning: Warning: Failed prop type: Invalid prop `mt` of value `4px` supplied to `RadioButton`, expected one of [0,1,2,3,4,5,7] 

### Expected behaviour
run unit test on a radio button does not raise an error

### Reproducible example
https://codesandbox.io/s/dreamy-snyder-o5xl7?file=/src/index.js

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 49.2.0
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by sjohnson-sage** [comment] 2020-11-23 17:53
Hi @jerlau I'm afraid that error is correct, 4px is currently not valid for the `mt` prop on `RadioButton` - https://github.com/Sage/carbon/blob/master/src/__experimental__/components/radio-button/radio-button.component.js

This component does not yet have the styled-system spacing props added to it so that prop can only be one of `[0,1,2,3,4,5,7]` which are multipliers of `8px`

**Comment by sjohnson-sage** [comment] 2020-11-23 17:54
@jerlau if you need the styled-system spacing props added to `RadioButton` now we can create a ticket for that as a feature request?

**Comment by sjohnson-sage** [comment] 2020-11-25 09:25
I'm going to close this issue as it's not a bug in Carbon, just the current behaviour of the `RadioButton` component

**Comment by jerlau** [comment] 2020-11-25 16:41
@sjohnson-sage  Sorry to be late, I don't see the notification on it. If you saw the sandbox, i don't use the mt prop and It raised a warning on it, that's the problem, we don"t fill an optionnal property and a warning is raised when we run unit test

**Comment by sjohnson-sage** [comment] 2020-11-25 16:50
Apologies @jerlau I misinterpreted the issue there, I will reopen

**Comment by sjohnson-sage** [comment] 2020-11-25 16:54
This is caused by https://github.com/Sage/carbon/blob/3acacda960ef02e03577a09f38ea9c374d28c584/src/__experimental__/components/radio-button/radio-button-group.component.js#L103 

We either need to change this, or add the styled-system spacing props to RadioButton (which is due to be done anyway)

**Comment by sjohnson-sage** [comment] 2020-11-25 16:58
FE-3373

**Comment by ianforster-sage** [comment] 2021-03-09 14:15
Resolved in https://github.com/Sage/carbon/releases/tag/v66.12.0

**Closed by ianforster-sage** 2021-03-09 14:15 UTC
Labels: Bug, On Backlog, Squad Petrus
