### ISSUE TITLE
FlatTable - When using screen reader, capability to sort column is not communicated to user

### ISSUE THREAD

**Issue by Alec-Walker-Sage** [Sage/carbon#3361] opened 2020-11-06 13:39 UTC
### Current behaviour
When using a screenreader the sortable column headings do not describe themselves as sortable. The current behaviour describes the heading as an empty group while in-fact it is a button. There is no indication that the heading is selectable. 

### Expected behaviour
The screen reader should provide some more information to the user, it should describe how the table is currently sorted and that pressing the button can sort the table. Example (Sortable column, activate to sort column descending)

### Reproducible example
1) Open the public Carbon storybook 

2) Navigate to Flat Table / test / sortable 

3) Turn of screen reader 

4) Access the table through the screen reader 

5) Visit the headings

### Suggested solution(s)
At the column - types of sorting available (found online)**

Use abbr to provide a short header for reading in cells
Modify the aria-label to indicate how the column will be sorted on next action (sort column-name type-of-sort)
type-of-sort = ascending/descending, A-Z, Z-A, increasing/decreasing, etc.
Modify the title on <button>s.to indicate how the column will be sorted on next action.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 48.5.0
| carbon-factory   |
| react-scripts    | 
| React            | 
| Browser          | Chrome (Mac Voice Over) 
| npm              |
| Operating System | Catalina

**Comment by nicktitchmarsh** [comment] 2020-11-11 10:31
This issue is a duplicate of https://github.com/Sage/carbon/issues/3222

**Closed by nicktitchmarsh** 2020-11-11 10:31 UTC
Labels: Bug, triage
