### ISSUE TITLE
Alert component Typescript definition changes

### ISSUE THREAD

**Issue by PaulSumner-Sage** [Sage/carbon#4455] opened 2021-10-04 14:55 UTC
### Current behaviour

Alert component TypeScript interface extends that of Dialog which also doesn’t have children defined on it, meaning trying to use Alert throws Type warnings:
```
Type '{ children: string; onCancel: () => void; open: boolean; subtitle: string; title: string; }' is not assignable to type 'IntrinsicAttributes & DialogProps'.
  Property 'children' does not exist on type 'IntrinsicAttributes & DialogProps'.ts(2322)
```

Additionally: Title prop of Alert component should also be `React.ReactNode`

### Expected behaviour

Alert to allow children, and Title to have Type of ReactNode

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/?path=/docs/alert--default-story

### JIRA Ticket (Sage Only)

SBS-13167

### Carbon Version

84.1.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by jamime** [comment] 2021-10-05 13:41
Duplicate of #4449

**Closed** 2021-10-05 13:41 UTC
Labels: Bug, triage
