### ISSUE TITLE
Table component styles don't render correctly when hovering selected field

### ISSUE THREAD

**Issue by carlcheel-sage** [Sage/carbon#2375] opened 2019-10-03 14:03 UTC
Carbon version: `v9.0.0-rc5`

Hovering over a selected row produces the following:

![image](https://user-images.githubusercontent.com/25386428/66133144-14799400-e5ee-11e9-98e9-02e9663c6afa.png)

I'd expect this to still use the selected style:

![image](https://user-images.githubusercontent.com/25386428/66133596-d892fe80-e5ee-11e9-8f7b-0b9c7aab0488.png)

**Comment by jamime** [comment] 2019-10-04 11:55
Thank you for reporting this @carlcheel-sage we've identified the cause and it is already fixed in #2346. Please feel free to report anything else you find, it really helps.

**Closed by jamime** 2019-10-04 11:55 UTC
