### ISSUE TITLE
Add padding and props for sidebar

### ISSUE THREAD

**Issue by maspychaj-sage** [Sage/carbon#5174] opened 2022-05-25 09:07 UTC
### Desired behaviour

I would like to specify padding inside the sidebar to add full width Message:

![image](https://user-images.githubusercontent.com/75613789/170225235-ced8c576-390f-49ce-8ced-b3e0e7fbd656.png)

### Current behaviour

Right now it's always 32px padding:

![image](https://user-images.githubusercontent.com/75613789/170225923-d9fca064-8b58-4f2d-8a4d-06b990057b14.png)

### Suggested Solution

Adding prop to specify padding.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/cool-meninsky-jx4iyh?file=/src/index.js

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment] 2022-05-27 07:49
duplicate of #4494

**Closed by edleeks87** 2022-05-27 07:49 UTC
Labels: Enhancement, triage
