### ISSUE TITLE
Reports tab - Form elements must have labels.

### ISSUE THREAD

**Issue by RavishankarSage** [Sage/carbon#5525] opened 2022-10-03 14:45 UTC
### Current behaviour

Reprts tab > main screen > Form elements must have labels.
![carbon-issues](https://user-images.githubusercontent.com/109725018/193606049-615066d5-3947-4c9a-8756-94f76622a8e2.png)

### Expected behaviour

Ensures every form element has a label

### CodeSandbox or Storybook URL

https://carbon.sage.com/v/109.2.2/index.html?path=/docs/flat-table-expandable--paginated

### JIRA Ticket (Sage Only)

SKPU-7033

### Carbon Version

109.2.2

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment] 2022-10-03 16:24
Duplicate of #5284

**Closed by edleeks87** 2022-10-03 16:24 UTC
Labels: Bug, triage
