### ISSUE TITLE
Unable to show a previously set value on a lazily loaded FilterableSelect

### ISSUE THREAD

**Issue by limcoc** [Sage/carbon#3576] opened 2021-01-12 16:26 UTC
### Current behaviour
I have a lazily loaded filterable select akin to [this example in the documentation](https://carbon.sage.com/?path=/docs/design-system-select-filterable--basic#infinite-scroll-example). My issue is that this control is used to modify existing data, so on initial load (before options have loaded) should be able to display the value that was previously set. At the moment I am only able to provide a value to the component, but if there is no child option that already has been loaded corresponding with that value, then there is no text to display on the select.

once I have opened the select and the options have loaded, if the control is then unfocused without selecting a different option, the correct option is then selected and displayed as is expected.

I have attempted to hack around this with adding an option for the first load without any success.

### Expected behaviour
At the time of initiaIisation I already know:
1. the value to select
2. the text relating to that value

I would like to be able to in some way manually set the text displayed within the select when it first loads to show the currently selected option prior to actually loading any of the options within the select.

### Reproducible example
https://codesandbox.io/s/cool-kilby-w9iuc?file=/src/BaseSelect.js

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 54.6.2 |

**Comment by sjohnson-sage** [comment] 2021-01-21 11:14
I'm going to close this because it's a duplicate of #3431 which we currently have on our backlog

**Closed by sjohnson-sage** 2021-01-21 11:14 UTC
Labels: Bug, triage
