### ISSUE TITLE
MultiSelect component - Error when we manage the value to display

### ISSUE THREAD

**Issue by hegou33** [Sage/carbon#3415] opened 2020-11-19 16:28 UTC
### Current behaviour

When we change the `Option` value of the `MultiSelect`, if a value that was previously selected is not anymore in the `Option`, we got an error, even if we clear the value props.
### Expected behaviour

We expect to be able to change the Option, so, manage the value to display.
### Reproducible example

https://codesandbox.io/s/dry-currying-vl4o7?file=/src/index.js
### Suggested solution(s)

![image](https://user-images.githubusercontent.com/38658070/99694044-4832aa00-2a8c-11eb-9853-8573b157a9b6.png)
Maybe don't use the selectedValue state when the component have controlled props.
### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 48.7.1
| carbon-factory   |
| react-scripts    | 
| React            | 16.8.6
| Browser          | Chrome
| npm              |
| Operating System | Windows

**Comment by grabkowski** [comment] 2020-11-19 18:10
Looks like there is a problem with that current example. The `useState` hook works asynchronously, so when you clear your value and change the current option list, the value is not yet cleared and that causes the issue.
To fix that you could use the `useEffect` hook and change the data, when the value has been cleared.

I have made some tweaks to that example, and looks like it works fine when the useEffect has been used:
https://codesandbox.io/s/determined-chatterjee-cubio

**Comment by jamime** [comment] 2020-11-26 10:27
Closing, I confirmed with @hegou33 that the solution provided by @grabkowski worked.

**Closed by jamime** 2020-11-26 10:27 UTC
Labels: Bug, Squad Petrus, resolved?, triage
