### ISSUE TITLE
Under certain circumstances the Select control ignores the first character typed

### ISSUE THREAD

**Issue by StevenMWood** [Sage/carbon#3131] opened 2020-08-12 15:23 UTC
### Current behaviour
Under certain circumstances, when then select control has focus, the first character typed by the user is ignored (swallowed) by the control.

### Expected behaviour
The first character typed into the control should be accepted.

### Reproducible example
This bug can be replicated easily on the Carbon Storybook site.
It occurs when using the "backspace" to delete a previous entry or when **PreventFocusAutoOpen** is enabled.

https://carbon.sage.com/?path=/story/experimental-select--classic

**Bug 1**
Select the control
Type black, then down arrow, then enter (so that it’s selected).
Tab into source story
Shift tab back to select. 
Text is highlighted
Use backspace key
Then type amber; the first char doesn’t appear.

**Bug 2**
In lower half of screen: Go to knobs tab. 
Select preventFocusAutoOpen
Click on Story Source
Shift tab into the select control. 
Type black; the first character is missing.

### Suggested solution(s)
As per the expected behaviour.

### Additional context
None

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 35.2.0 |
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          | Chrome |
| npm              |
| Operating System | Windows 10 |

**Comment by jamime** [comment] 2020-08-17 09:40
@StevenMWood this should be fixed in the `Select` component that is listed in `Design System`. The `__experimental__` one is due to be removed. Sorry for any confusion.

https://carbon.sage.com/?path=/docs/design-system-select--basic

**Comment by jamime** [comment] 2020-08-24 09:46
I've confirmed both of these are fixed in the new `Select` component.

**Closed by jamime** 2020-08-24 09:46 UTC
Labels: Bug, resolved?, triage
