### ISSUE TITLE
MultiSelect component - Keyboard accessibility, not able to select option

### ISSUE THREAD

**Issue by hegou33** [Sage/carbon#4438] opened 2021-09-29 12:59 UTC
### Current behaviour

We cannot browse the list of options with the keyboard. We have to use the filter function to select an option.

### Expected behaviour

To be able to select an option without the filter option.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/select-multiselect--default-story

### JIRA Ticket (Sage Only)

SBS-20270

### Carbon Version

87.0.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by sjohnson-sage** [comment] 2021-09-29 13:18
Duplicate of https://github.com/Sage/carbon/issues/3602, closing. Please search through the issues before raising one to make sure one doesn't already exist

**Closed by sjohnson-sage** 2021-09-29 13:18 UTC
Labels: Bug, triage
