### ISSUE TITLE
Message Component with a List has two bullet points when read with screenreader

### ISSUE THREAD

**Issue by JohnOxleySage** [Sage/carbon#4406] opened 2021-09-16 13:35 UTC
### Current behaviour

Currently when there is a message with a list and the screenreader reads the whole message it reads two bullet points per listItem. 

### Expected behaviour

It's expected that only one bullet point will be read. 

### CodeSandbox or Storybook URL

https://codesandbox.io/s/new-pond-hvfug

### JIRA Ticket (Sage Only) ###

RIV-518

### Suggested Solution

Message from Martin Underhill about this issue:
Ah interesting. I tend to check most of my new work in Firefox because it’s a bit more fussy about special characters. From a VoiceOver point of view, though, don’t worry about flagging it unless it happens in Safari. Firefox has only recently added VoiceOver support (less than a year, I think) so there are lots of quirks.
But if there’e on square there in Safari, it might just be a case of adding a hide-from-screenreaders  prop. That might not exist, of course, but if it does, it’d probably add aria-hidden="true" or role="presentation" which would treat it like a decorative image: nice visually, but ultimately not that important as the “There is a problem” heading and its content do the real work

### Carbon Version

76.1.3

### What browsers are you seeing the problem on?

Firefox

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by sianford** [comment] 2021-09-16 13:46
RIV-514

**Comment by sjohnson-sage** [comment] 2021-09-21 12:38
Hi @JohnOxleySage - Martin's comment you posted there says don't worry about flagging it unless it happens in Safari, but you've raised the issue against Firefox. Does this only happen in Firefox? If so it looks like we might be able to just close this, thanks

**Comment by sianford** [comment] 2021-09-28 19:23
Confirmed with @JohnOxleySage, the issue occurs when an error Message is triggered dynamically from a particular option chosen from the Select menu. Updated the codesandbox to the correct example. Tested in Safari, Chrome, Firefox and Edge. The issue occurs in all the browsers, with the addition in Firefox of part of the error bullet text being read out twice.

**Comment by sianford** [comment] 2021-09-28 19:54
FE-4366

**Comment by DipperTheDan** [comment] 2022-06-21 12:29
So after some research in to this, I’m not fully convinced this is a Carbon issue. Message has an `role="status"` which means it gets `aria-live="polite"` out of the box. There is known bug with `aria-live` where it reads out twice on Mac using VoiceOver. This can be seen on [the .gov website for character count](https://design-system.service.gov.uk/components/character-count/). It reads out the characters remaining twice.

I got around Safari reading black square for a bullet point by adding `role="presentation"` on to the List element. [Here is the codesandbox for you to take a look at](https://codesandbox.io/s/jovial-grass-4k5pw4?file=/src/index.js). 

If you're happy with this workaround, I'll get the issue closed off.

**Comment by DipperTheDan** [comment] 2022-07-01 13:17
As there has been no response regarding my solution [here](https://github.com/Sage/carbon/issues/4406#issuecomment-1161684534) I am going to close the issue. Please drop me a message if you need this issue re-opening.

**Closed by DipperTheDan** 2022-07-01 13:17 UTC
Labels: Bug, On Backlog, Squad Rivia, message
