### ISSUE TITLE
DatePicker - Default value raises warning when using blank string

### ISSUE THREAD

**Issue by damianOfKyan** [Sage/carbon#5405] opened 2022-08-22 16:52 UTC
### Current behaviour

>Warning: Failed prop type: Invalid prop `selectedDays` of type `String` supplied to `ForwardRef`, expected instance of `Date`.
Carbon raises error when value is set to empty string ie value='', yet its absolutely ok when given date as a string ie: '2022-07-01'.

### Expected behaviour

DatePicker should accept empty string value without raising error.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/carbon-date-picker-selected-date-bug-vhgtmx?file=/src/index.js

### Carbon Version

109.2.2

### Design Tokens Version

2.21.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment] 2022-08-23 10:04
Sounds like the same issue as #5333

**Comment by edleeks87** [comment] 2022-08-23 10:36
Closing this as it's a duplicate of the issue @DipperTheDan has mentioned above. This is caused by the `parseDate` util returning an empty string instead of `null` when the value is falsy/ empty. The issue is fixed in https://github.com/Sage/carbon/pull/5383 and should be released soon

**Closed by edleeks87** 2022-08-23 10:36 UTC
Labels: Bug, triage, date
