### ISSUE TITLE
Integrate highlighted prop ActionPopover/FlatTableRowHeader /FlatTableRow 

### ISSUE THREAD

**Issue by hagad** [Sage/carbon#3476] opened 2020-12-08 13:17 UTC
### Current behaviour
I raised this issue after analysing the put in place of  highlighted prop on ActionPopover/FlatTable.
I'am based on the example provided by @jamime  https://codesandbox.io/s/flat-table-action-popover-3455-1l0ds?file=/src/index.js
To facilitate the exchange I created this sandBox https://codesandbox.io/s/gracious-waterfall-w90rj?file=/src/index.js  : 
Problem 1 : The highlighted prop doesn't exist in **FlatTableRowHeader** that we use in our table.
Problem 2 : if you open the menu of the popover action, and you click on the row to open the  dialog:
The menu remains displayed in the dialog => My be we have to manage this with setOpen ?
Problem 3 : Management of onOpen and onClose of the send box you provided need to be improved:
 - In the SendBox we can open 2 menu
 - Sometimes the row stays highlighted after closing the menu.

### Expected behaviour

- See Detail in https://github.com/Sage/carbon/issues/3455 which is closed.

### Reproducible example
https://codesandbox.io/s/gracious-waterfall-w90rj?file=/src/index.js 

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 51.0.0
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by jamime** [comment] 2020-12-09 10:06
- 1 should be a straight forward CSS improvement.
- I think 2 & 3 are both caused by the event not closing the menu here.
https://github.com/Sage/carbon/blob/ef3dc675c81394543069ba70dd04fec21915e887/src/components/action-popover/action-popover.component.js#L71-L86

**Comment by sjohnson-sage** [comment] 2020-12-09 10:29
We're wondering why you need to add a `highlighted` prop to `FlatTableRowHeader`? You can select the whole row as intended here. `FlatTableRowHeader` is just a cell, and cells currently do not have the `highlighted` prop by design

We will create a task on our backlog for points 2 and 3 and await more information on point 1. Maybe speak to UX about point 1 and ask if it's needed to highlight a single cell

**Comment by sjohnson-sage** [comment] 2020-12-09 10:33
FE-3414 for points 2 and 3

**Comment by jamime** [comment] 2020-12-09 10:59
This is what is currently achievable, I _think_ the `FlatTableRowHeader` should also be highlighted. @harpalsingh / @lukeemmerson-finch can you confirm?

![image](https://user-images.githubusercontent.com/2328042/101621298-7d884300-3a0d-11eb-8f60-d182c8a981b3.png)

**Comment by lukeemmerson-finch** [comment] 2020-12-10 16:58
@jamime yes i agree that the left flat table row header cell should also be highlighted in this scenario.

**Comment by ianforster-sage** [comment] 2020-12-10 17:04
FE-3425 for point 1

**Closed** 2020-12-18 10:01 UTC
Labels: Bug, On Backlog, Squad Petrus
