### ISSUE TITLE
Confirm component typescript definition file is inaccessible

### ISSUE THREAD

**Issue by kishanivelupillai-sage** [Sage/carbon#3806] opened 2021-03-09 16:34 UTC
### Current behaviour
Confirm component has a typescript definition that is inaccessible when using import statement as follows -
`import Confirm from "carbon-react/lib/components/confirm";`

### Expected behaviour
Enable Confirm component typescript definition to be accessible when using import statement as follows -
`import Confirm from "carbon-react/lib/components/confirm";`

### Reproducible example
N/A

### Suggested solution(s)
Provide an index.d.ts file that will export the typescript definition for Confirm component

### Additional context
N/A

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |   v66.18.0
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by sjohnson-sage** [comment] 2021-03-10 13:03
I'm closing this as it's a duplicate of https://github.com/Sage/carbon/issues/3710

**Closed by sjohnson-sage** 2021-03-10 13:03 UTC
Labels: Bug, triage
