### ISSUE TITLE
Flat Table: We cannot mix hasStickyHead and pagination

### ISSUE THREAD

**Issue by jerlau** [Sage/carbon#3076] opened 2020-07-16 15:11 UTC
### Current behaviour
We've ot a bad rendering of the last page on a flat table when we mixed hasStickyHead (with an height defined on componant) and pagination
![image](https://user-images.githubusercontent.com/17121053/87687671-4d9e8180-c786-11ea-961d-8e5a50c15b81.png)

### Expected behaviour
no empty space between the end of the flatTable and the pager object.

### Reproducible example
https://codesandbox.io/s/musing-snow-gs0uh

### Workaround
Count the number of line that you want to show, Deduce the page height.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 34.0.2
| carbon-factory   |
| react-scripts    |  3.0.1
| React            | 16.8.6
| Browser          | chrome
| npm              |
| Operating System | window 10

**Comment by jamime** [comment] 2020-07-20 09:52
Duplicate of #3072

**Closed by jamime** 2020-07-20 09:52 UTC
Labels: Bug, triage
