### ISSUE TITLE
Dialog Full Screen component reports 5 accessibility violations: 

### ISSUE THREAD

**Issue by DianeGit22** [Sage/carbon#4793] opened 2022-02-04 17:39 UTC
### Current behaviour

Dialog Full Screen component "with complex example" story reports 5 accessibility violations (carbon.sage.com): 
![image](https://user-images.githubusercontent.com/47564230/152576054-2936534b-33de-4856-a3e3-2ed083f2099f.png)

### Expected behaviour

No accessibility violations should occur. 

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/dialog-full-screen--with-complex-example

### Carbon Version

Latest

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment] 2022-02-08 14:13
Looks like partly a duplicate of #4692. I will add these issues to that ticket

**Comment by nicktitchmarsh** [comment] 2022-02-08 14:32
FE-4922

**Closed** 2022-02-22 11:07 UTC
Labels: Bug, On Backlog, Squad Front End
