### ISSUE TITLE
Decimal component: crashes if only decimal delimiter entered

### ISSUE THREAD

**Issue by blaky** [Sage/carbon#3844] opened 2021-03-19 15:10 UTC
### Current behaviour

When the user enters just a dot into the decimal component and then blurs the field, the application crashes.

![image](https://user-images.githubusercontent.com/4557844/111801524-56bf8f80-88cd-11eb-8ee2-e15f85f5a888.png)

Same happens if you enter `.,`

### Expected behaviour
The application would not crash. 

### Reproducible example
https://carbon.sage.com/?path=/story/experimental-decimal-input-test--default
https://codesandbox.io/s/red-firefly-di671?file=/index.js

**Comment by blaky** [comment] 2021-03-22 14:52
Closing in favour of the other bug report on the same issue.

**Comment by ianforster-sage** [comment] 2021-03-23 09:54
Duplicate of https://github.com/Sage/carbon/issues/3372

**Closed by ianforster-sage** 2021-03-23 09:54 UTC
Labels: Bug, triage
