### ISSUE TITLE
Experimental textarea doesn't support rows

### ISSUE THREAD

**Issue by basalter** [Sage/carbon#2666] opened 2020-02-24 09:54 UTC
### Current behaviour
Experimental textarea doesn't span the specified number of rows

### Expected behaviour
When setting the rows property of the textarea component, the rendered textarea spans that number of rows

### Reproducible example
https://codesandbox.io/s/recursing-perlman-f2h0f

### Suggested solution(s)
The height css property must be unset for text area
![image](https://user-images.githubusercontent.com/40786353/75142591-b6ac2c80-56f3-11ea-9531-f033a9ff6cbd.png)

### Your environment
| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 13.1.0, 12.0.0
| carbon-factory   | CodeSandbox
| react-scripts    | CodeSandbox
| React            |CodeSandbox
| Browser          |CodeSandbox
| npm              |CodeSandbox
| Operating System | CodeSandbox

**Comment by jamime** [comment] 2020-02-24 10:24
Closing as duplicate of #2637

Happy to accept a PR if you need a quick turnaround.

**Closed by jamime** 2020-02-24 10:24 UTC
Labels: Bug, triage

**Comment by basalter** [comment] 2020-02-24 11:21
Not sure about the PR polices, but https://github.com/Sage/carbon/pull/2667 should do the thing
