### ISSUE TITLE
Issue with MultiSelect dropdown in Dialog Component

### ISSUE THREAD

**Issue by hagad** [Sage/carbon#5502] opened 2022-09-26 07:51 UTC
### Current behaviour

If we add a MultiSelect component in the Dialog: 
The dropdown is not opened in the good area.

### Expected behaviour

The dropdown should be opened like https://carbon.sage.com/?path=/docs/select-multiselect--default-story
We have this issue since carbon version 110.4.1

### CodeSandbox or Storybook URL

https://codesandbox.io/s/shy-bush-6o35nh?file=/src/index.js

### Carbon Version

110.10.3

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by robinzigmond** [comment] 2022-09-26 08:24
duplicate of https://github.com/Sage/carbon/issues/5465

**Closed by robinzigmond** 2022-09-26 08:24 UTC
Labels: Bug, triage
