### ISSUE TITLE
Toast Notification UI Z-Index Issues

### ISSUE THREAD

**Issue by SivalenSivalingam** [Sage/carbon#3621] opened 2021-01-29 11:22 UTC
### Current behaviour
when a toast notification is displayed on top left, our navigation chevron icon / selected element seem to have a higher z-index to toast notification UI.

![image](https://user-images.githubusercontent.com/2328042/106883090-6ac18000-66d7-11eb-8a8c-a35eb3f6a5b3.png)

![image](https://user-images.githubusercontent.com/2328042/106883099-6eed9d80-66d7-11eb-9966-7f45750e3fac.png)

### Expected behaviour
Our toast notification to have a higher index placement so any element should be cover by the toast notification UI.

### Reproducible example
Display a toast notification top left with a navigation chevron icon directly under the UI
https://codesandbox.io/s/great-cache-t5fm1

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react    | 59.0.0

Report By Klendathu Squad

**Comment by jamime** [comment] 2021-02-04 10:57
FE-3680

**Comment by jamime** [comment] 2021-02-04 10:59
Duplicate of #3627 / FE-3680

**Closed by jamime** 2021-02-04 10:59 UTC
Labels: Bug, Squad Klendathu, triage
