### ISSUE TITLE
MenuItem cannot be disabled

### ISSUE THREAD

**Issue by damienrobson-sage** [Sage/carbon#4153] opened 2021-06-11 10:51 UTC
### Current behaviour
The `MenuItem` component no longer appears to be able to be disabled

### Desired behaviour
I should be able to pass a `disabled` prop to a MenuItem to disable it and appropriately style it

### Suggested solution
As above

### Describe alternatives you've considered
I've tried a styling override but the layout of the button means that the custom styling is complex and likely to break in future releases

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 76.1.3
| react-scripts    | 3.4.4
| React            | 16.13.1
| Browser          | Chrome
| npm              | 6.14.4
| Operating System | macOS Catalina

**Comment by nicktitchmarsh** [comment] 2021-06-15 14:14
Hi @damienrobson-sage, could you provide an example of the use case where you need to be able to disable a menu item? Wouldn't you just not show menu items that are inaccessible? Is this pattern approved by the UX/DS team?
Thanks.

**Comment by damienrobson-sage** [comment] 2021-06-16 09:05
HI @nicktitchmarsh - I'd be happy to. In the new Online Bureau, we have a menu which lists the various endpoints a user can navigate to. This menu is controlled by two things: the applications your company is subscribed to, and the permissions you have. For example, a company has signed up to application X, but I as a user do not have permission to access X (I may have no permissions at all to access it, or I may have insufficient permissions e.g. I need managerial permissions but only have uploader permissions). In this instance, we want show the menu entry but disable it unless the user meets all requirements. 

This requirement has been deemed necessary by our BAs and as far as I'm aware that requirement was approved by the UX team when they designed the original screen. Hope that helps.

**Comment by dawidzarzycki** [comment] 2021-06-22 12:39
@harpalsingh Can you confirm this is correct with our Design System?

**Comment by harpalsingh** [comment] 2021-07-07 08:22
Currently we have no deisgns where there is an expectation to disable a MenuItem in the Menu component. @damienrobson-sage normally by design in Menus on permissions the item is not visible at all since it serves no purpose to the user and only gets in the way, can we not just follow that logic? Why would we want to show someone something they can't use at all.

**Comment by damienrobson-sage** [comment] 2021-07-07 08:52
@harpalsingh let me check with our BAs - if I can convince them that we can do without the feature, then there's no need to add this kind of support in.

**Comment by jamime** [comment] 2021-07-27 12:38
@damienrobson-sage did you get an update?

**Comment by damienrobson-sage** [comment] 2021-07-27 13:06
Hi @jamime - I did but forgot to leave it here. I spoke to one of our BAs and this feature is definitely something we require.

**Comment by jamime** [comment] 2021-07-27 13:26
@harpalsingh please can you or the design system team review and provide a spec.

**Comment by mmaciorowski-sage** [comment] 2021-08-10 12:47
Hi @harpalsingh do we have some more information about designs?

**Comment by nicktitchmarsh** [comment] 2021-12-07 14:14
Design system to confirm when a spec is available for this work

**Comment by nicktitchmarsh** [comment] 2022-03-16 09:39
@harpalsingh @ingridzillinger, are we able to close this issue and move the requirement into DSY?

**Comment by ingridzillinger** [comment] 2022-03-22 14:45
Before we include this in the DSY backlog, I would like an assessment from @v99rly
When we use disabled menu items that are not yet clickable due to missing rights and/or submissions: How do we let users know what the cause is? How do keyboard users and screen reader users deal with this?

**Comment by ingridzillinger** [comment] 2022-04-06 12:00
The current status of this topic can be tracked in the design system backlog: [DSY-1485](https://jira.sage.com/browse/DSY-1485)

**Comment by ingridzillinger** [comment] 2022-05-09 15:46
Design system team: From today's perspective, we will not expand the design system's menu component with disabled menu items.
Reason
The Design System team's goal is to deliver fully accessible components so that all users can use them and we don't exclude anyone. Fully accessible means that we aim for the highest standard. This ensures that our personas Anne, Manuel and Mary - representative of all people - can use a Sage product. Business requirements and user needs must be aligned. Perhaps an innovative approach can lead to a solution - think of how iOS would do it.

**Closed** 2022-05-10 07:06 UTC
Labels: Enhancement, On Backlog, menu
