### ISSUE TITLE
Sidebar not responsive as per the screen size, post scroll fix

### ISSUE THREAD

**Issue by sagemihir** [Sage/carbon#5458] opened 2022-09-08 14:43 UTC
### Current behaviour

Post the fix of the sidebar `position="fixed" `to be static and not scroll with the right side of the page, the sidebar is not responsive and is not able to settle at the bottom, please refer the video.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/dreamy-night-4nqw2q?file=/src/index.js:928-1013

### JIRA Ticket (Sage Only)

SBS-32854

### Carbon Version

110.2.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment] 2022-10-04 13:18
Hi @sagemihir, please could you amend the codesandbox to show an example of responsive behaviour you would expect to work? Currently the codesandbox you linked in the issue is not a responsive example, as it will always show the two `Box`es side by side. You can achieve the responsive behaviour you are looking for using our custom `useMediaQuery` hook to create a breakpoint for small screen sizes. If there is a problem with this hook, please let us know.

**Comment by TSageSpencer** [comment] 2022-10-07 05:12
Hi, @sagemihir and @Parsium,

Just wondering where this is up to?

**Comment by sagemihir** [comment] 2022-10-10 06:51
Hi @TSageSpencer ,

Would try to look into this issue asap, the only question I have is with the current implementation, if the sidebar is not `"fixed"`it works fine and is responsive. Should it not behave the same with the current implementation and keep the sidebar fixed ?

Thanks

**Comment by TSageSpencer** [comment] 2022-10-10 07:07
Hi @sagemihir,

I believe that is what we want correct: We want the implementation to be responsive exactly the same but the side bar just you be fixed so that when the user scrolls they aren't cutting the figures head off

**Comment by Parsium** [comment] 2022-10-25 15:09
Hi @sagemihir, do you have any further updates regarding this issue? Does using the `useMediaQuery` hook solve your issue?

**Comment by sagemihir** [comment] 2022-10-26 12:36
Hi @Parsium , as I mentioned in the previous messages, the current implementation of the sidebar does not require the use of `useMediaQuery` and the sidebar is adaptive as per the screen sized without using them. I doubt if this should change when the side bars vertical scroll is fixed ?.

**Comment by Parsium** [comment] 2022-12-08 11:27
Update on this issue - upon investigating the problem with @sagemihir in the Quick Start Wizard project - this seemed to be a local CSS issue. I have proposed a solution for this on the project repository for further consideration. 

Given this no longer requires a carbon fix, I will close this issue, but of course feel free to contact me @sagemihir if you and your team encounter any further problems 👍🏼

**Closed by Parsium** 2022-12-08 11:27 UTC
Labels: Bug, More Information Required
