### ISSUE TITLE
Interacting with the `Select` causes the entire screen to disappear in Storybook

### ISSUE THREAD

**Issue by thedannygoodall** [Sage/carbon#4936] opened 2022-03-06 19:42 UTC
### Current behaviour

When interacting with a few examples of the `Select` component within the, the entire screen disappears and becomes nothing but whitespace. Only a few of the `Select` components do this, some work fine. This is caused by...

> TypeError: Cannot create property 'count' on string '[Object]'

https://user-images.githubusercontent.com/28150291/156939375-74c31438-f2c3-495d-b02a-44d4481634b4.mov

### Expected behaviour

For the screen to not revert to whitespace, and for the `Select` to function as expected. 

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/select--default-story

### Carbon Version

104.48.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

I have not checked to see if this still happens when consuming the `Select` in an application, I've only checked the Storybook. 

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment] 2022-03-07 16:08
duplicate of #4878

**Closed by edleeks87** 2022-03-07 16:08 UTC
Labels: Bug, triage
