### ISSUE TITLE
Inconsistent typing for spacing props on buttons

### ISSUE THREAD

**Issue by MarkMizenSagecom** [Sage/carbon#3735] opened 2021-02-22 13:39 UTC
### Current behaviour
The MarginSpacingProps type accepts a number or string for the margin prop (ml, mr etc.) types.

https://github.com/Sage/carbon/blob/352570da66b99c84a77cf0e25ad93d926c9e8fde/src/utils/helpers/options-helper/options-helper.d.ts

This is overwritten for the Button component. 

https://github.com/Sage/carbon/blob/master/src/components/button/button.d.ts

mb only accepts numbers from 1 to 7, and ml only accepts a string.

### Expected behaviour
These props to be consistent across all components in the library.

### Reproducible example
https://codesandbox.io/s/nifty-curran-539bs?file=/src/index.tsx

### Suggested solution(s)
Remove the ml and mb props on the ButtonProps interface: https://github.com/Sage/carbon/blob/master/src/components/button/button.d.ts

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by sjohnson-sage** [comment] 2021-02-23 09:22
Hi @MarkMizenSagecom I'm going to close this as a duplicate of https://github.com/Sage/carbon/issues/3727 - with a note for that one to cover both `mb` and `ml`

**Closed by sjohnson-sage** 2021-02-23 09:22 UTC
Labels: Bug, triage
