### ISSUE TITLE
Tabs component incompatible with url parameters or hash routing

### ISSUE THREAD

**Issue by MarkMizenSagecom** [Sage/carbon#3573] opened 2021-01-11 16:15 UTC
### Current behaviour

When changing tab using the tabs component it calls window.history.replaceState to add a hash to the url. This prevents the use of the tabs for applications with hash routing or with url parameters which are intended to be persistent.

### Expected behaviour
- URL parameters should be preserved when switching tabs

### Suggested solution(s)
- There should be an option to disable the history.replaceState behaviour for applications that need to use hash routing
- call to replaceState should preserve url parameters:

https://github.com/Sage/carbon/blob/0e405e7c4e4dd843e605ce27ea79e443ca43e410/src/components/tabs/__internal__/tabs.component.js#L109
```ts
const url = `${_window.location.origin}${_window.location.pathname}${_window.location.search}#${tabid}`;
```

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |  54.6.2 |
| carbon-factory   |  |
| react-scripts    |  4.0.1 |
| React            | 17.0.1 |
| Browser          | chrome |
| npm              | 6.14.6 |
| Operating System | Windows 10 |

**Comment by jamime** [comment] 2021-01-12 10:26
Related: https://github.com/Sage/carbon/issues/3520#issuecomment-750097762

**Comment by sjohnson-sage** [comment] 2021-01-21 11:15
@jamime is this a duplicate of #3520 and if so can we close this one?

**Comment by jamime** [comment] 2021-01-29 14:07
> @jamime is this a duplicate of #3520 and if so can we close this one?

It's not a duplicate, but will be fixed with the solution that I proposed.

@MarkMizenSagecom You can set the prop `setLocation=false` to disable this behaviour.

**Comment by jamime** [comment] 2021-02-04 10:08
Closing, users can use `setLocation=false` and `onTabChange` to maintain their own history #3520 FE-3484 will improve the interface to use the provided navigator/history.

**Closed by jamime** 2021-02-04 10:08 UTC
Labels: Bug, triage
