### ISSUE TITLE
FilterableSelect dont set lazy value

### ISSUE THREAD

**Issue by ardvi** [Sage/carbon#3592] opened 2021-01-20 06:24 UTC
### Current behaviour
In FilterableSelect component, set the value by lazy
The FilterableSelect remains empty, without value.

Note : The Select works fine.

### Expected behaviour
When the value is set by lazy, FIlterableSelect must take this as current value.

### Reproducible example
In this codeSandBox, the same way is use to set the value in Select and FilterableSelect component : 

https://codesandbox.io/s/carbonlazyfilterableselectvalue-505y3?file=/src/index.js

The Select component take the value, the Filterable dont.

### Additional context
Maybe relative to these issues : 
https://github.com/Sage/carbon/issues/3576
https://github.com/Sage/carbon/issues/3431

### Your environment
| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react 52.0.0   |

**Comment by sjohnson-sage** [comment] 2021-01-21 10:32
FE-3596

**Comment by sjohnson-sage** [comment] 2021-01-21 10:33
It looks like #3431 is related to the issue but #3576 is not

**Comment by sjohnson-sage** [comment] 2021-01-21 10:35
This is a duplicate of #3431 so I'm going to close this issue

**Closed by sjohnson-sage** 2021-01-21 10:35 UTC
Labels: Bug, On Backlog
