### ISSUE TITLE
Dialog: centerDialog is inconsistent when it has a scrollbar

### ISSUE THREAD

**Issue by hegou33** [Sage/carbon#3470] opened 2020-12-04 10:32 UTC
### Current behaviour

If the content of the dialog changed and we got a scrollbar, the dialog is not center. Each time that we call the dialogRef.current.centerDialog(), the position of the dialog change.
![DialogCenter](https://user-images.githubusercontent.com/38658070/101153169-5b18b300-3624-11eb-83bd-94dab18cb199.gif)

### Expected behaviour

We expect that the dialog is center when we call the dialogRef.current.centerDialog() function.
### Reproducible example

https://codesandbox.io/s/vibrant-heisenberg-5qv7u?file=/src/index.js:856-886
### Suggested solution(s)

![image](https://user-images.githubusercontent.com/38658070/101152369-42f46400-3623-11eb-9938-f24b9c4303ac.png)
Maybe using this._dialog.scrollHeight instead of this._dialog.offsetHeight.
### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 50.3.0
| carbon-factory   |
| react-scripts    | 
| React            | 16.8.6
| Browser          | Chrome
| npm              |
| Operating System | Windows

**Comment by jamime** [comment] 2020-12-04 10:42
Duplicate of #3411

**Comment by jamime** [comment] 2020-12-04 10:47
I've re opened this. This issue is relating to the call to `centerDialog`, not that automatic re-positioning as requested in #3411.

**Comment by jamime** [comment] 2020-12-04 10:51
FE-3405

**Closed** 2021-01-11 08:55 UTC
Labels: Bug, On Backlog, Squad Petrus
