### ISSUE TITLE
`FilterableSelect`:  `inputValue` and `selectedValue` mismatch

### ISSUE THREAD

**Issue by JinCoreana** [Sage/carbon#6493] opened 2023-12-21 10:03 UTC
### Current behaviour

**Scenario 1.**
1. I type `item` in the input, then don’t select anything.
2. trigger onBlur by clicking outside of the component
3. `item0` is in the input but the selected value is `undefined`

**Scenario 2.**
1. I select `item4` from the dropdown
2. remove ‘4’ by Backspace keyboard event
3. trigger onBlur by clicking outside of the component
4. `item0` is in the input but the selected value is `item4`

### Expected behaviour

**Scenario 1.**
Expected 3: `Please select…`is displayed in the input and the selected value is `undefined`

**Scenario 2.**
Expected 4: `item4` stays in the input and as the selected value

### CodeSandbox or Storybook URL

https://l466m4.csb.app/

### JIRA Ticket (Sage Only)

SBS-79881

### Carbon Version

124.4.1

### Design Tokens Version

4.23.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by sianford** [comment] 2024-01-02 14:27
FE-6314

**Comment by robinzigmond** [comment] 2024-01-02 14:34
hi @JinCoreana, this is happening because you have a controlled component but are only updating the value when a "selection confirmed" event happens on change - with a controlled component the value will never update unless you do it explicitly. You can fix the 2 scenarios you list by adding an `onBlur` - see here https://codesandbox.io/s/select-carbon-forked-mfl2yz?file=/src/CustomSelect.js

Please let us know if there are any reasons why this solution is not satisfactory for you - if not we can raise a ticket, but we need a better understanding of why `onBlur` does not work as a solution.

**Comment by JinCoreana** [comment] 2024-01-02 15:20
> hi @JinCoreana, this is happening because you have a controlled component but are only updating the value when a "selection confirmed" event happens on change - with a controlled component the value will never update unless you do it explicitly. You can fix the 2 scenarios you list by adding an `onBlur` - see here https://codesandbox.io/s/select-carbon-forked-mfl2yz?file=/src/CustomSelect.js
> 
> Please let us know if there are any reasons why this solution is not satisfactory for you - if not we can raise a ticket, but we need a better understanding of why `onBlur` does not work as a solution.

Hi @robinzigmond, thank you for the idea. I think `onBlur` can resolve my issue case for now however there is still a corner case in your example here https://codesandbox.io/s/select-carbon-forked-mfl2yz?file=/src/CustomSelect.js
If you try :

1 . I select `item4` from the dropdown
2. remove ‘4, m ’ by Backspace keyboard event
3. trigger `onBlur` by clicking outside of the component
4. `item0` is displayed within the input but the selected value is `ite`

So if I add more manual logic as shown here https://hj3ksw.csb.app/
```
  const onBlur = (event) => {
    const updatedValue = optionList.find((option) =>
      option.props.name.includes(event.target.value)
    );
    setValue(updatedValue.props.value);
  };
```
It seems the corner case has been resolved. However, I wonder if this should be the default behaviour in the package, as I believe the selected value and displayed input value should always align.

**Comment by robinzigmond** [comment] 2024-01-02 15:41
FE-6317

**Comment by robinzigmond** [comment] 2024-01-22 10:27
Hello @JinCoreana,

After spending some time looking at this issue, I've reached the conclusion that we shouldn't attempt a "fix" for this in Carbon.

So there are various reasons, mostly to do with [allowing options with an object as their value](https://carbon.sage.com/?path=/docs/select-filterable--with-object-as-value), why we need to keep the value in the textbox separate from the value prop. I'm not really sure if these are still needed to be honest - but we have a large piece of work upcoming (which will kick off with an RFC, so keep your eyes peeled for that!) to do a major rewrite of select, we'll definitely make sure this is one of the many areas we bring to light.

Further, examples like yours (as well as most in our docs to be fair), where each option's `value` prop is different from its text value, are tricky - in fact I realised when playing with your example more that the `onBlur` I suggested that you add doesn't quite work as you'd want, because that sets the value to the textbox value (that's what the `event.target.value` in the `onBlur` callback is, and has to be), when what you wanted is the underlying option value. And that means you've got no choice but to add a bit of code exactly like you quoted in your last comment, to convert from one to the other.

While we could indeed have the Carbon component doing this automatically, I don't think it's appropriate to do that on blur, because that would assume that consumers always want a blur event to trigger a change event, which I don't think is a valid - or expected - assumption. Further, even doing that wouldn't actually work for your example, because your `onChange` explicitly checks the `selectionConfirmed` property, and even if we do call `onChange` from `onBlur` I don't think we should treat that as selection being confirmed. Again, these are things that consumers can easily do as they need in their own code - as you have demonstrated, and I don't think Carbon should go too far in making assumptions about what consumers want.

I will thank you for raising this though, as while investigating I noticed a related small edge-case issue with deleting content from the textbox, which I do intend to fix as that's straightforward and looks like a simple code mistake to me!

I'm going to close the issue, but please reply if you think there's a reason to still proceed with a fix, in light of what I've said above!

**Closed by robinzigmond** 2024-01-22 10:27 UTC
Labels: Bug, On Backlog, Squad SBC Miro
