### ISSUE TITLE
Pager - click on page size selection causes the input area to be shortened and the vertical scroll bar to disappear

### ISSUE THREAD

**Issue by arvig33** [Sage/carbon#4909] opened 2022-02-28 09:53 UTC
### Current behaviour

When we click on page size selection of the Pager component,  causes the input area to be shortened and the vertical scroll bar of the page to disappear.

### Expected behaviour

When you click on the page size selection of the Pager component, the size of the input field must not be changed and the vertical scroll bar of the page must not disappear.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/pager-issue-96p05i

### Carbon Version

104.33.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment] 2022-02-28 09:57
Duplicate of #4860

**Comment by arvig33** [comment] 2022-03-14 15:29
With Carbon version 104.54.2, the vertical scroll bar always disappears when you click on page size selection.

**Comment by nicktitchmarsh** [comment] 2022-03-29 13:05
@arvig33 this sounds like a separate issue. I will raise a new issue and close this one as we have fixed the original task

**Closed by nicktitchmarsh** 2022-03-29 13:05 UTC
Labels: Bug, triage, pager
