### ISSUE TITLE
Dialog : add more possibilities to contentPadding

### ISSUE THREAD

**Issue by gusch** [Sage/carbon#5984] opened 2023-04-20 13:49 UTC
### Desired behaviour

Have a standard padding at the bottom 

![image](https://user-images.githubusercontent.com/16415182/233386586-600ed2e7-281d-446d-94ab-32919d551c2e.png)

### Current behaviour

In a Form, Carbon automatically add a 24px margin-bottom for each inputs.
If the input is the last thing in a dialog, the space at the bottom is too much.

![image](https://user-images.githubusercontent.com/16415182/233386906-69d44cca-3c65-4650-bf57-f01b8324f445.png)

### Suggested Solution

Dialog have the contentPadding prop but it is not possible to override just the bottom one.
```
export interface ContentPaddingInterface {
    p?: PaddingValues;
    py?: PaddingValues;
    px?: PaddingValues;
}
```

Maybe add the possibility to override pt/pr/pb/pl so that we can remove the padding-bottom when the last thing in the dialog is an input.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/nervous-dan-okx6bt?file=/src/App.js

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by robinzigmond** [comment] 2023-04-25 12:48
@ljemmo are you happy with this suggestion? It seems reasonable to me but we don't want to allow consumers to implement designs that don't meet DS approval.

**Comment by ljemmo** [comment] 2023-04-25 16:37
@robinzigmond i don't think you'd ever have a form without a button, so is this ever a realistic scenario? My gut feel is not to open up padding options here as this may drive inconsistency pan-sage. Rather, if padding is an issue, perhaps we should bake in a specific padding amount of last-of-type or last-child.

**Comment by gusch** [comment] 2023-04-26 07:15
I didn't place buttons in the example because they are not usefull here to demonstrate the problem.
But of course we have buttons (in stickyFooter) in our use cases.

We obtain that 
![image](https://user-images.githubusercontent.com/16415182/234497958-05e7e677-5cd7-41a9-a630-3231f5995120.png)

UX would prefer that 
![image](https://user-images.githubusercontent.com/16415182/234498607-0f4d46db-f420-4e9d-8ac4-02b3f7cc6b33.png)

**Comment by ljemmo** [comment] 2023-05-02 14:18
@gusch  and @Parsium I caught up with claire and apparently the original dialog with 40px at the bottom was by design. This was so that form elements are deliberately visually separated from the footer. For this reason, i think we can close this issue?

**Closed** 2023-05-03 08:27 UTC
Labels: Enhancement, triage, Design System Review Required
