### ISSUE TITLE
FilterableSelect throws an exception when an invalid value is entered and the Enter key is hit

### ISSUE THREAD

**Issue by matcic** [Sage/carbon#6021] opened 2023-05-11 15:44 UTC
### Current behaviour

The [default example](https://carbon.sage.com/?path=/docs/select-filterable--default) using the `FilterableSelect` component throws an exception whenever the user types an invalid value and hits  the `Enter` key.

Please check [this CodeSanbox example](https://codesandbox.io/s/ecstatic-night-u5y88l?file=/src/App.js) to reproduce the issue. 

### Expected behaviour

 The `FilterableSelect` should not throw an exception when some random input is entered and the `Enter` key is hit.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/ecstatic-night-u5y88l?file=/src/App.js

### Carbon Version

118.2.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

The error is being thrown by [this line](https://github.com/Sage/carbon/blob/master/src/components/select/filterable-select/filterable-select.component.tsx#L436) because `textValue` is `undefined`. 

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by blaky** [comment] 2023-05-12 07:52
It doesn't crash with 114.11.0, it is a recent regression

**Comment by nicktitchmarsh** [comment] 2023-05-16 12:56
FE-5890

**Comment by edleeks87** [comment] 2024-02-21 14:46
It looks like this was addressed in the above PR and released in [v123.7.0](https://github.com/Sage/carbon/pull/6395#issuecomment-1802262458). I'm going to close this but please feel free to re-open if you find this not to be the case

**Closed by edleeks87** 2024-02-21 14:46 UTC
Labels: Bug, On Backlog
