### ISSUE TITLE
Tabs - screen goes black when trying to access tab prop in Firefox

### ISSUE THREAD

**Issue by divyajindel** [Sage/carbon#5038] opened 2022-04-10 22:54 UTC
### Current behaviour

https://user-images.githubusercontent.com/88449494/162643246-220c603b-4d08-4252-b229-0fe29eb6be87.mov

### Expected behaviour

This issue should not occur.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/tabs--without-extended-dividing-line

### Carbon Version

latest

### What browsers are you seeing the problem on?

Firefox

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment] 2022-04-12 12:58
Hi @divyajindel - is this just caused by clicking on lots of stories in quick succession? If so I don't think it's really an issue that we need to look into, we can just close this.

Feel free to reach out to me if you think we should investigate this further

**Closed by samtjo** 2022-04-12 12:58 UTC
Labels: Bug, triage
