### ISSUE TITLE
MenuItem onClick event is not called.

### ISSUE THREAD

**Issue by jlongridge** [Sage/carbon#3866] opened 2021-03-31 10:19 UTC
### Current behaviour
An `onClick` event defined for a `MenuItem` (with sub-menu items) is not called when clicked. 

### Expected behaviour
Expected defined `onClick` function to be called.

### Reproducible example
https://codesandbox.io/s/falling-surf-y98ho?file=/src/index.js

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 66.0.0
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by DipperTheDan** [comment] 2021-04-01 09:22
@harpalsingh @tempertemper - What are you opinions on this request from John? 

Due to an ongoing conversation between John and UX/Solutions Design, more info will be required.

**Comment by tempertemper** [comment] 2021-04-02 12:16
@DipperTheDan I'm not sure what the expected behaviour is for this component. Guessing pressing the main button trigger the link and hovering causes the sub-menu to appear, allowing a mouse/track user to those a specific product version. I have my concerns about the hover-to-trigger the submenu as it would be:

- Confusing for touch users (where tapping the button would show the menu, and tapping again would trigger the main/parent link); would they know they could follow the main/parent link?
- impossible to reach the submenu for keyboard, screen reader, and speech recognition users

Is this component being used in the wild, or part of the Carbon library yet? I'd be happy to offer some time to discuss the user need that drove the component and work out an alternative, more accessible solution.

**Comment by ianforster-sage** [comment] 2021-04-08 09:52
Will discuss privately with @jlongridge & @tempertemper to agree next steps.

**Comment by ianforster-sage** [comment] 2021-04-15 08:28
Out come of the discussion with @jlongridge and @tempertemper is that the missing `onClick` event handler should be fixed so let's go ahead and raise a story for that. How it should be used is a different usability question that will be resolved by UX.

**Comment by mkrds** [comment] 2021-04-15 09:47
FE-4027

**Comment by sjohnson-sage** [comment] 2021-05-10 16:20
This was fixed in https://github.com/Sage/carbon/releases/tag/v71.0.0 - looks like the PR link didn't close the issue!

**Closed by sjohnson-sage** 2021-05-10 16:20 UTC
Labels: Bug, On Backlog, Squad Rocket
