### ISSUE TITLE
Decimal fields crashes app if "^" is used on Mac.

### ISSUE THREAD

**Issue by KevinSchmidtSage** [Sage/carbon#3372] opened 2020-11-12 09:43 UTC
### Current behaviour
If you try to type ^ into a decimal carbon field on a Mac (Firefox, Chrome) it will crash the react app with an error saying that your entry is not a decimal number.

### Expected behaviour
Decimal fields should also permit typing of ^ on Mac, as it does on windows.

### Your environment
carbon-react Version 48.6.2
macOS Catalina 10.15.6
Firefox 82.0.3

**Comment by jamime** [comment] 2020-11-12 14:05
Hi @KevinSchmidtSage 

The decimal component shouldn't allow you to input a `^`.
I tried with the following versions and could not reproduce your issue. I used the following story to test https://carbon.sage.com/?path=/story/experimental-decimal-input--default

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |48.6.3
| Browser          | Firefox  82.0.3
| Operating System | macOS Catalina 10.15.7

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |48.6.3
| Browser          | Chrome 86.0.4240.193 
| Operating System | macOS Catalina 10.15.7

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |48.6.3
| Browser          | Safari 14.0 (15610.1.28.1.9, 15610)
| Operating System | macOS Catalina 10.15.7

Please can you verify that your keycode information matches the following
![image](https://user-images.githubusercontent.com/2328042/98949527-c244bb00-24ef-11eb-86ca-7e989f47ab70.png)

Go to https://keycode.info/ and press the key that causes the problem for you.

Failing that, if you can provide a codesandbox with a reproducible example we can investigate this further.

**Comment by jamime** [comment] 2020-11-18 10:10
I've contacted @KevinSchmidtSage on teams for more information.

**Comment by KevinSchmidtSage** [comment] 2020-11-18 13:44
Sorry for my late answer. If I press ^ on my MacBook keyboard (which still crashes the app within a decimal field) on key code.info it returns this:
<img width="1408" alt="Bildschirmfoto 2020-11-18 um 14 42 02" src="https://user-images.githubusercontent.com/50820376/99537913-89ec2380-29ac-11eb-8e0f-bc1eb4688424.png">

Additional info:
At our app, it doesn't avoid typing in "^". I can type ^ and after I leave the decimal field (focus), the app crashes. I will check that again now, to be sure, that nothing else causes that problem at our app.

**Comment by KevinSchmidtSage** [comment] 2020-11-18 13:46
Nevermind. My fault! I found the problem (we have some self coded validation stuff going on around carbon.)... sorry and thanks for your help! :(

**Comment by KevinSchmidtSage** [comment] 2020-11-18 14:07
Okay, I removed our validation wrapper for testing. Still same issue. I tried to type "^" inside of Decimal field at carbon.sage.com and I get the same error! carbon.sage.com website crashes with "^" is not a number.

At your video, you can't type "^" and the field is shaking instantly. At my Mac, I Can type ^ and onBlur, it crashes the app :(. any ideas?

**Comment by jamime** [comment] 2020-11-18 14:29
I think this is a difference between our locales. What keyboard layout are you using? Please can you share a screenshot of your keyboard settings. To enter the `^` I press `Shift` + `6`.

![image](https://user-images.githubusercontent.com/2328042/99542766-57412b80-29aa-11eb-83e7-b0343c9d47ce.png)

**Comment by sjohnson-sage** [comment] 2020-11-18 14:29
Do you know why you're getting a "Dead" key event when you press "^"? This problem might be specific to the way your keyboard is set up

**Comment by KevinSchmidtSage** [comment] 2020-11-18 14:34
Veeery interesting... I have a German keyboard layout, where "^" is one button at the left of "1". If I type Shift+6 it does: &

<img width="769" alt="Bildschirmfoto 2020-11-18 um 15 31 26" src="https://user-images.githubusercontent.com/50820376/99543410-6d9fb500-29b3-11eb-97cf-f23404bed27e.png">

If I type Shift+6 at key code info I receive the same Number but with my different event type (& - Because of German layout)...
<img width="1332" alt="Bildschirmfoto 2020-11-18 um 15 32 42" src="https://user-images.githubusercontent.com/50820376/99543507-8a3bed00-29b3-11eb-8cd6-9380f4f07d61.png">

**Comment by jamime** [comment] 2020-11-18 15:37
I've managed to reproduce this by changing my keyboard layout to `German`

![image](https://user-images.githubusercontent.com/2328042/99551284-9031ce00-29b3-11eb-862f-b2dc0a71a732.png)

I've created ticket FE-3334 on our backlog.

**Comment by ianforster-sage** [comment] 2021-02-09 15:26
The fix in #3635 has not been merged. We have agreed with our architects to try a new approach. 
Ref: FE-3705

**Comment by blaky** [comment] 2021-03-22 14:51
Probably duplicates https://github.com/Sage/carbon/issues/3844

**Comment by blaky** [comment] 2021-04-06 14:22
Any update on this?

**Closed** 2021-05-11 12:51 UTC
Labels: Bug, On Backlog, Squad SBC Germany
