### ISSUE TITLE
Flat Table: We cannot mix hasStickyHead and pagination

### ISSUE THREAD

**Issue by jerlau** [Sage/carbon#3072] opened 2020-07-15 16:00 UTC
### Current behaviour
An empty line appears (in yellow) at the end of the list

![image](https://user-images.githubusercontent.com/17121053/87566606-8b86a180-c6c3-11ea-9b8e-3e3253f8f3ce.png)

### Expected behaviour
This empty line must be removed

### Reproducible example
https://codesandbox.io/s/cranky-cloud-j5rpt?file=/src/index.js:3915-3928

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 33.3.0
| carbon-factory   | 11.0.1 (none in sandbox)
| react-scripts    | 3.0.1
| React            | 16.8.6(sandbox) and 16.13.1 (client managment)
| Browser          | Chrome Version 83.0.4103.116 (Build officiel) (64 bits)
| npm              | 6.13.7
| Operating System | windows 10

**Comment by jamime** [comment] 2020-07-20 09:48
Closing as duplicate of #3076

**Comment by jamime** [comment] 2020-07-20 09:55
Confirmed in 35.1.1 without any additional CSS
![image](https://user-images.githubusercontent.com/2328042/87924857-5f7a7000-ca77-11ea-8c12-b8988fe907d1.png)

 FE-2956

**Comment by jerlau** [comment] 2020-07-20 14:16
Hi, There is no problem if you remove the column popover (the last in this case).

**Comment by ianforster-sage** [comment] 2020-08-20 10:36
FE-2956

**Closed** 2020-11-19 16:38 UTC
Labels: Bug, On Backlog, Squad Petrus
