### ISSUE TITLE
Pages animation bug when using keyboard nav

### ISSUE THREAD

**Issue by DipperTheDan** [Sage/carbon#3374] opened 2020-11-12 13:13 UTC
### Current behaviour
When using keyboard navigation with the Pages component, the animation can sometimes glitch and appear to shift off the left of the screen. 

![Pages_Master_bug](https://user-images.githubusercontent.com/56251247/98944046-590d7980-24e8-11eb-95bc-a7aaa7fb5ea9.gif)

### Expected behaviour
Animation should not glitch like this.

### Reproducible example
https://carbon.sage.com/?path=/story/pages--default

### Suggested solution(s)
Fix animation with Pages component.

### Additional context
N/A

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 48.6.3
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          | Chrome
| npm              |
| Operating System | Mac OS Catalina v10.15.6

**Comment by sjohnson-sage** [comment] 2020-11-18 11:01
This could be a storybook issue because it's in an iFrame, we have tried it outside of an iFrame and it seems to behave correctly. 
We need a reproducible example of this outside of storybook otherwise I think we can close this as a non-issue

**Comment by DipperTheDan** [comment] 2020-12-01 16:48
I've knocked up this codesandbox: 
https://codesandbox.io/s/musing-elbakyan-7gfed?file=/src/index.js

Looks like it must be a Storybook specific issue. I think it can be closed as a non-issue in that case.

**Closed** 2020-12-01 17:07 UTC
Labels: Bug, More Information Required, Squad Front End, triage
