### ISSUE TITLE
Date picker positioning is out when label is inline

### ISSUE THREAD

**Issue by toni-leigh** [Sage/carbon#1491] opened 2017-08-18 13:30 UTC
## Problem

The date picker pop-up does appear in the correct position when label is set to inline

![image](https://user-images.githubusercontent.com/10499070/29460811-35a35976-8421-11e7-9576-17d32bebcd39.png)

## Solution

Positioning is tweaked, with the date picker appearing left aligned on stacked fields (no code editing required:
![image](https://user-images.githubusercontent.com/10499070/29460861-66c9ef42-8421-11e7-8e4f-7a81c38e5c7e.png)

But also, this is achieved when label is inline:
![image](https://user-images.githubusercontent.com/10499070/29460968-db6db784-8421-11e7-83de-388637006068.png)

We also ensure that the date picker position will not be affected by css applied to the parent, possibly by isolating it in a div to avoid flex effects, and also that the distance between the label and field is not relevant.

## Done means

- [ ] Specs are written and component edited accordingly.
- [ ] Definition and demo site example works.
- [ ] Demo site text is added to.

**Comment by toni-leigh** [comment] 2017-08-18 13:42
Note, it's only the edge of the screen that counts, this is fine:

![image](https://user-images.githubusercontent.com/10499070/29461386-6da1f4a2-8423-11e7-8c69-7ad5c646d01f.png)

**Comment by andrewjtait** [comment] 2017-08-22 15:54
duplicate of https://github.com/Sage/carbon/issues/644

**Closed by andrewjtait** 2017-08-22 15:54 UTC
Labels: Bug
