### ISSUE TITLE
Pager input has uneeded margin

### ISSUE THREAD

**Issue by andreiamar** [Sage/carbon#5650] opened 2022-11-28 16:39 UTC
### Current behaviour

When having the Pager component inside a Form, the pager's current page input has a margin-bottom applied that makes the input misaligned with the rest of the elements inside the pager.

### Expected behaviour

The Pager should not be affected when nested inside a Form component.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/gracious-elgamal-ire590

### JIRA Ticket (Sage Only)

SBS-43506

### Carbon Version

111.0.0

### Design Tokens Version

2.42.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by jamime** [comment] 2022-11-28 16:40
This is caused by the Form input spacing. This should be 0 on the pager.

**Comment by mkrds** [comment] 2022-11-29 13:37
FE-5565

**Comment by robinzigmond** [comment] 2022-12-06 10:41
apologies, it was believed that this was fixed but we've just realised the issue is still there. We'll get a proper fix released ASAP.

**Closed** 2022-12-07 09:20 UTC
Labels: Bug, On Backlog, released
