### ISSUE TITLE
Tile: (Responsive behaviour) Allow the Tile width to be controlled by the content 

### ISSUE THREAD

**Issue by amieedwards-sage** [Sage/carbon#7033] opened 2024-10-23 15:45 UTC
### Description

I am building out a Responsive Tile layout using `<FlexTileContainer>` and `<FlexTileCell>`

What I expect is that the width of the `<Tile>` is responsive and is determined by the content inside of it.

What actually happens is that the `<Tile>` either spans the full width of the page. 
We try to avoid using hard-coded pixel width values due to the dynamic nature of the content that is being rendered.
So, after exploring an alternative solution of wrapping it in a `<Box>` with `maxWidth: ‘fit-content’` this resulted in the last `<FlexTileCell>` wrapping onto a new line despite there being available space for the Tile to grow.

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-wkqnp7?file=src%2FApp.tsx

### Carbon version

142.13.0

### Design tokens version

4.34.0

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment] 2024-10-29 14:18
FE-6879

**Comment by nuria1110** [comment] 2024-10-31 10:37
Looks like this issue is caused by `flex-basis` being set to "160px" by default on FlexTileCell. Using your provided demo and setting `flexBasis="auto"` seems to achieve the expected behaviour, `width="fit-content"` can also be set on Tile if you don't want to wrap the component with Box:  https://stackblitz.com/edit/parsium-carbon-starter-xzruz2?file=src%2FApp.tsx

**Comment by amieedwards-sage** [comment] 2024-10-31 15:31
Hi @nuria1110 

Thanks for taking a look at this. 
I've looked at the stackblitz that you've shared, while the `Tile` now takes the width of the content, when the screen-size is reduced and the flex tile cells are dropping to stack into a single column there is still a big white space that is not caused by the content and seems to be caused by some internal mechanism of the component (see screenshot).

Ideally we would want the width of `fit-content` to be respected and the Tile `width` to be reduced as per the content.

![Screenshot 2024-10-31 at 15 26 21](https://github.com/user-attachments/assets/ee6db83f-3833-4e0b-893e-1c61c8962438)

**Comment by nuria1110** [comment] 2024-11-12 10:29
Closing as the component behaves as expected for a flex container, we will be adding support to Tile for grid layouts as part of FE-6896.

**Closed by nuria1110** 2024-11-12 10:29 UTC
Labels: Bug, On Backlog
